
spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/rovies
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/rovies
    user: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

tmdb:
  access-token: [YOUR_ACCESS_TOKEN]
